version: '3'

services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports:
      - "8080:8080"
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
    command: "/usr/local/bin/envoy -c /etc/envoy.yaml"

